Repository jenkinsci/pipeline-graph-view-plugin, pull requests merged in 2021-07, with the labels that each got.

#15 Pipeline console log - alpha
  package-lock.json
  package.json
  src/main/frontend/common/reset-environment.ts
  src/main/frontend/pipeline-console-view/app.tsx
  src/main/frontend/pipeline-console-view/index.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/DataTreeView.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/PipelineConsole.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/index.ts
  src/main/frontend/pipeline-console-view/pipeline-console/main/pipeline-console.scss
  src/main/frontend/pipeline-graph-view/app.scss
  src/main/frontend/pipeline-graph-view/app.tsx
  src/main/frontend/pipeline-graph-view/index.tsx
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/PipelineGraph.tsx
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/PipelineGraphLayout.ts
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/PipelineGraphModel.tsx
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/index.ts
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/support/StatusIcons.tsx
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/support/SvgSpinner.tsx
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/support/SvgStatus.tsx
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/support/TruncatingLabel.tsx
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/support/startPollingPipelineStatus.ts
  src/main/frontend/pipeline-graph-view/pipeline-graph/styles/PipelineGraphWidget.scss
  src/main/frontend/pipeline-graph-view/pipeline-graph/styles/main.scss
  src/main/frontend/pipeline-graph-view/pipeline-graph/styles/variables.scss
  src/main/java/io/jenkins/plugins/pipelinegraphview/PipelineGraphViewAction.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/consoleview/PipelineConsoleViewAction.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/consoleview/PipelineConsoleViewActionFactory.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/AbstractPipelineViewAction.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/BlueRun.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/FlowNodeWrapper.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/NodeRunStatus.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineGraph.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineGraphApi.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineNodeGraphVisitor.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineNodeUtil.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineStage.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineStageInternal.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineStep.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineStepApi.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineStepList.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineStepVisitor.java
  src/main/resources/io/jenkins/plugins/pipelinegraphview/consoleview/PipelineConsoleViewAction/index.jelly
  src/main/resources/io/jenkins/plugins/pipelinegraphview/consoleview/PipelineConsoleViewAction/sidepanel.jelly
  src/test/java/io/jenkins/plugins/pipelinegraphview/PipelineGraphApiTest.java
  tsconfig.json
  webpack.config.js
Labels: enhancement

#24 Split the PipelineGraph component into smaller ones
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/PipelineGraph.tsx
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/support/connections.tsx
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/support/labels.tsx
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/support/nodes.tsx
Labels: chore

#25 Makes indentation consistent on labels.tsx
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/support/labels.tsx
Labels: chore

#26 Ansi color support, convert urls to links, integrate jest testing framework
  .babelrc
  package-lock.json
  package.json
  src/main/frontend/pipeline-console-view/pipeline-console/main/Ansi.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/Linkify.spec.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/Linkify.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/PipelineConsole.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/pipeline-console.scss
  src/main/frontend/setupTests.js
Labels: enhancement, test

#23 ConsoleView: Recursively get steps for all stages (and child stages)
  src/main/frontend/pipeline-console-view/pipeline-console/main/DataTreeView.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/index.ts
  src/main/java/io/jenkins/plugins/pipelinegraphview/PipelineGraphViewAction.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/consoleview/PipelineConsoleViewAction.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/AbstractPipelineViewAction.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineGraphApi.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineStepApi.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineStepVisitor.java
  src/test/java/io/jenkins/plugins/pipelinegraphview/PipelineGraphApiTest.java
  src/test/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineGraphApiTest.java
  src/test/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineStepApiTest.java
  src/test/java/io/jenkins/plugins/pipelinegraphview/utils/TestUtils.java
  src/test/resources/io/jenkins/plugins/pipelinegraphview/utils/complexParallelSmokes.jenkinsfile
  src/test/resources/io/jenkins/plugins/pipelinegraphview/utils/complexSmokes.jenkinsfile
  src/test/resources/io/jenkins/plugins/pipelinegraphview/utils/unstableSmokes.jenkinsfile
Labels: enhancement

#30 Fix graph url when accessed from sub-path
  src/main/resources/io/jenkins/plugins/pipelinegraphview/PipelineGraphViewAction/action.jelly
Labels: bug

#27 Integrate prettier for frontend code style
  .prettierignore
  .prettierrc.json
  package-lock.json
  package.json
  src/main/frontend/common/reset-environment.ts
  src/main/frontend/pipeline-console-view/app.tsx
  src/main/frontend/pipeline-console-view/index.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/Ansi.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/DataTreeView.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/Linkify.spec.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/Linkify.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/PipelineConsole.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/index.ts
  src/main/frontend/pipeline-console-view/pipeline-console/main/pipeline-console.scss
  src/main/frontend/pipeline-graph-view/app.tsx
  src/main/frontend/pipeline-graph-view/index.tsx
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/PipelineGraph.tsx
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/PipelineGraphLayout.ts
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/PipelineGraphModel.tsx
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/index.ts
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/support/StatusIcons.tsx
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/support/SvgSpinner.tsx
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/support/SvgStatus.tsx
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/support/TruncatingLabel.tsx
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/support/connections.tsx
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/support/labels.tsx
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/support/nodes.tsx
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/support/startPollingPipelineStatus.ts
  src/main/frontend/pipeline-graph-view/pipeline-graph/styles/PipelineGraphWidget.scss
  src/main/frontend/pipeline-graph-view/pipeline-graph/styles/main.scss
  src/main/frontend/setupTests.js
Labels: chore

#28 Integrate spotless for java code style
  CONTRIBUTING.md
  pom.xml
  src/main/java/io/jenkins/plugins/pipelinegraphview/PipelineGraphDisplayURLProvider.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/PipelineGraphViewAction.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/PipelineGraphViewActionFactory.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/consoleview/PipelineConsoleViewAction.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/consoleview/PipelineConsoleViewActionFactory.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/AbstractPipelineViewAction.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/BlueRun.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/FlowNodeWrapper.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/NodeRunStatus.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineGraph.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineGraphApi.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineNodeGraphVisitor.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineNodeUtil.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineStage.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineStageInternal.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineStep.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineStepApi.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineStepList.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineStepVisitor.java
  src/test/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineGraphApiTest.java
  src/test/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineStepApiTest.java
  src/test/java/io/jenkins/plugins/pipelinegraphview/utils/TestUtils.java
Labels: chore

#35 Change ID from integer to string
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineGraphApi.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineStage.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineStageInternal.java
Labels: bug

#36 Make compatible with themes
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/support/labels.tsx
  src/main/frontend/pipeline-graph-view/pipeline-graph/styles/PipelineGraphWidget.scss
Labels: feature

#38 Add the step args to the display name.
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/FlowNodeWrapper.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineNodeUtil.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineStepApi.java
  src/test/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineStepApiTest.java
  src/test/resources/io/jenkins/plugins/pipelinegraphview/utils/complexParallelSmokes.jenkinsfile
Labels: feature

#41 Redirect to logs page on node graph click
  src/main/frontend/pipeline-graph-view/app.tsx
Labels: feature
