Repository jenkinsci/pipeline-graph-view-plugin, pull requests merged in 2022-10, with the labels that each got.

#137 Update webpack from 4.x to 5.x
  package-lock.json
  package.json
Labels: dependencies

#157 Add scrollbar to list of steps in Console view
  src/main/frontend/pipeline-console-view/pipeline-console/main/PipelineConsole.tsx
Labels: enhancement

#148 Console: Add timing information for steps and stages.
  src/main/frontend/pipeline-console-view/pipeline-console/main/DataTreeView.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/PipelineConsole.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/pipeline-console.scss
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/PipelineGraphLayout.spec.ts
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/PipelineGraphModel.tsx
  src/main/java/io/jenkins/plugins/pipelinegraphview/consoleview/PipelineConsoleViewAction.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineGraphApi.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineStage.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineStageInternal.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineStep.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineStepApi.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineStepVisitor.java
Labels: enhancement

#159 Add scrollbar to console text pane
  src/main/frontend/pipeline-console-view/pipeline-console/main/PipelineConsole.tsx
Labels: enhancement

#164 Set the step display name to only the label if set
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/FlowNodeWrapper.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineStepApi.java
Labels: enhancement

#133 Use Jenkins pre-formatted log messages.
  package-lock.json
  package.json
  src/main/frontend/pipeline-console-view/pipeline-console/main/Ansi.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/Linkify.spec.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/Linkify.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/PipelineConsole.tsx
  src/main/java/io/jenkins/plugins/pipelinegraphview/consoleview/PipelineConsoleViewAction.java
Labels: enhancement

#167 Convert blue ocean icons to jenkins icons for the pipeline graph
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/support/StatusIcons.tsx
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/support/SvgStatus.tsx
  src/main/frontend/pipeline-graph-view/pipeline-graph/styles/PipelineGraphWidget.scss
Labels: enhancement

#174 Revert "Convert blue ocean icons to jenkins icons for the pipeline graph"
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/support/StatusIcons.tsx
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/support/SvgStatus.tsx
  src/main/frontend/pipeline-graph-view/pipeline-graph/styles/PipelineGraphWidget.scss
Labels: bug

#178 Convert blue ocean icons to jenkins icons for the pipeline graph
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/support/StatusIcons.tsx
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/support/SvgStatus.tsx
  src/main/frontend/pipeline-graph-view/pipeline-graph/styles/PipelineGraphWidget.scss
Labels: enhancement

#177 Expand tree view to a reasonable step by default
  src/main/frontend/pipeline-console-view/pipeline-console/main/PipelineConsole.tsx
Labels: enhancement
