Repository jenkinsci/pipeline-graph-view-plugin, pull requests merged in 2022-09, with the labels that each got.

#64 Update POM, remove JSR 305 and code modernization
  pom.xml
  src/main/java/io/jenkins/plugins/pipelinegraphview/PipelineGraphViewActionFactory.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/consoleview/PipelineConsoleViewActionFactory.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/multipipelinegraphview/MultiPipelineGraphViewActionFactory.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/FlowNodeWrapper.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/NodeRunStatus.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineNodeGraphVisitor.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineNodeUtil.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineStepVisitor.java
  src/test/java/io/jenkins/plugins/pipelinegraphview/utils/TestUtils.java
Labels: chore

#71 Simplify graph API tests
  src/main/frontend/multi-pipeline-graph-view/app.tsx
  src/main/frontend/multi-pipeline-graph-view/multi-pipeline-graph/main/SingleRun.tsx
  src/main/frontend/multi-pipeline-graph-view/multi-pipeline-graph/styles/main.scss
  src/test/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineGraphApiTest.java
  src/test/java/io/jenkins/plugins/pipelinegraphview/utils/TestUtils.java
Labels: test

#73 Fix tree representation for scripted parallel stages
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineGraphApi.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineNodeGraphVisitor.java
  src/test/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineGraphApiTest.java
  src/test/resources/io/jenkins/plugins/pipelinegraphview/utils/scriptedParallel.jenkinsfile
Labels: bug

#72 Use tree representation for graph layout
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/PipelineGraph.tsx
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/PipelineGraphLayout.spec.ts
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/PipelineGraphLayout.ts
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/PipelineGraphModel.tsx
Labels: bug

#76 Automate updating node version
  renovate.json
Labels: chore

#75 Update baseline and dependencies
  package-lock.json
  pom.xml
  src/test/java/io/jenkins/plugins/pipelinegraphview/utils/TestUtils.java
Labels: chore

#74 Remove unused graph code
  src/main/java/io/jenkins/plugins/pipelinegraphview/multipipelinegraphview/MultiPipelineGraphViewAction.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/AbstractPipelineViewAction.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineGraphApi.java
  src/test/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineGraphApiTest.java
Labels: chore

#80 Remove unused sidepanels
  src/main/resources/io/jenkins/plugins/pipelinegraphview/PipelineGraphViewAction/index.jelly
  src/main/resources/io/jenkins/plugins/pipelinegraphview/PipelineGraphViewAction/sidepanel.jelly
  src/main/resources/io/jenkins/plugins/pipelinegraphview/consoleview/PipelineConsoleViewAction/index.jelly
  src/main/resources/io/jenkins/plugins/pipelinegraphview/consoleview/PipelineConsoleViewAction/sidepanel.jelly
  src/main/resources/io/jenkins/plugins/pipelinegraphview/multipipelinegraphview/MultiPipelineGraphViewAction/index.jelly
  src/main/resources/io/jenkins/plugins/pipelinegraphview/multipipelinegraphview/MultiPipelineGraphViewAction/sidepanel.jelly
Labels: enhancement

#84 Console view UI improvements
  src/main/frontend/pipeline-console-view/pipeline-console/main/pipeline-console.scss
  src/main/java/io/jenkins/plugins/pipelinegraphview/consoleview/PipelineConsoleViewAction.java
Labels: enhancement

#83 Recurse into child stages to flatten the tree
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/PipelineGraphLayout.spec.ts
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/PipelineGraphLayout.ts
Labels: bug

#86 Include synthetic stages in graph and console logs
  src/main/frontend/pipeline-console-view/pipeline-console/main/DataTreeView.tsx
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/PipelineGraphModel.tsx
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/support/labels.tsx
  src/main/frontend/pipeline-graph-view/pipeline-graph/styles/PipelineGraphWidget.scss
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/FlowNodeWrapper.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineGraphApi.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineNodeGraphVisitor.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineNodeUtil.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineStage.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineStageInternal.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineStepVisitor.java
  src/test/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineGraphApiTest.java
  src/test/resources/io/jenkins/plugins/pipelinegraphview/utils/syntheticStages.jenkinsfile
Labels: enhancement

#88 Remove parallel branches from graph if they weren't run
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineNodeGraphVisitor.java
  src/test/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineGraphApiTest.java
  src/test/resources/io/jenkins/plugins/pipelinegraphview/utils/skippedParallel.jenkinsfile
Labels: bug

#94 Fix stage view
  src/main/java/io/jenkins/plugins/pipelinegraphview/multipipelinegraphview/MultiPipelineGraphViewAction.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/AbstractPipelineViewAction.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineGraphApi.java
  src/test/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineGraphApiTest.java
Labels: bug

#102 Run prettier
  src/main/frontend/pipeline-console-view/pipeline-console/main/pipeline-console.scss
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/PipelineGraphLayout.spec.ts
Labels: chore

#126 docs: Fix the contribution guidelines link
  README.md
Labels: documentation

#129 Revert "Update dependency linkifyjs to v3.0.5 #103"
  package-lock.json
  package.json
Labels: bug

#132 Use CSS class for synthetic stages styling in console view
  src/main/frontend/pipeline-console-view/pipeline-console/main/DataTreeView.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/pipeline-console.scss
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/support/labels.tsx
  src/main/frontend/pipeline-graph-view/pipeline-graph/styles/PipelineGraphWidget.scss
Labels: bug

#90 Add clickable line numbers to console view
  package-lock.json
  src/main/frontend/pipeline-console-view/app.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/DataTreeView.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/PipelineConsole.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/pipeline-console.scss
  src/main/java/io/jenkins/plugins/pipelinegraphview/consoleview/PipelineConsoleViewAction.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineStep.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineStepApi.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineStepList.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineStepVisitor.java
Labels: enhancement

#131 Add card layout, add job / build titles, adjust color on console screen for dark-theme
  .gitignore
  package-lock.json
  package.json
  pom.xml
  src/main/frontend/multi-pipeline-graph-view/multi-pipeline-graph/main/SingleRun.tsx
  src/main/frontend/pipeline-console-view/app.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/DataTreeView.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/PipelineConsole.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/pipeline-console.scss
  src/main/frontend/pipeline-graph-view/_cards.scss
  src/main/frontend/pipeline-graph-view/app.scss
  src/main/frontend/pipeline-graph-view/index.tsx
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/support/labels.tsx
  src/main/frontend/pipeline-graph-view/pipeline-graph/styles/PipelineGraphWidget.scss
  src/main/frontend/scm/SCM.tsx
  src/main/frontend/status-icon/StatusIcon.tsx
  src/main/frontend/step-status/StepStatus.tsx
  src/main/java/io/jenkins/plugins/pipelinegraphview/PipelineGraphViewAction.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/cards/Card.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/cards/RunDetailsCard.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/cards/RunDetailsItem.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/cards/items/CauseRunDetailsItem.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/cards/items/GitHubBranchSourceRunDetailsItems.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/cards/items/SCMRunDetailsItems.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/cards/items/TimingRunDetailsItems.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/multipipelinegraphview/MultiPipelineGraphViewAction.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/AbstractPipelineViewAction.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineGraphApi.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineStepVisitor.java
  src/main/resources/io/jenkins/plugins/pipelinegraphview/PipelineGraphViewAction/index.jelly
  src/main/resources/io/jenkins/plugins/pipelinegraphview/consoleview/PipelineConsoleViewAction/index.jelly
  src/main/resources/io/jenkins/plugins/pipelinegraphview/multipipelinegraphview/MultiPipelineGraphViewAction/index.jelly
  src/main/resources/lib/pipeline-graph-view/card.jelly
  src/main/resources/lib/pipeline-graph-view/taglib
  src/main/webapp/js/build.js
  src/main/webapp/js/card.js
  webpack.config.js
Labels: enhancement

#134 Add separator to card
  src/main/frontend/pipeline-graph-view/_cards.scss
  src/main/java/io/jenkins/plugins/pipelinegraphview/PipelineGraphViewAction.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/cards/RunDetailsItem.java
  src/main/resources/io/jenkins/plugins/pipelinegraphview/PipelineGraphViewAction/index.jelly
Labels: enhancement
