Repository jenkinsci/pipeline-graph-view-plugin, pull requests merged in 2023-05, with the labels that each got.

#246 Rename 'Details' link to 'Graph' in consol view
  src/main/frontend/pipeline-graph-view/_cards.scss
  src/main/frontend/pipeline-graph-view/pipeline-graph/styles/main.scss
  src/main/java/io/jenkins/plugins/pipelinegraphview/PipelineGraphViewAction.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/AbstractPipelineViewAction.java
  src/main/resources/io/jenkins/plugins/pipelinegraphview/consoleview/PipelineConsoleViewAction/index.jelly
Labels: enhancement

#275 Suppress FlowInterruptedException stack traces
  pom.xml
  src/main/java/io/jenkins/plugins/pipelinegraphview/consoleview/PipelineConsoleViewAction.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineNodeUtil.java
  src/test/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineStepApiTest.java
  src/test/resources/io/jenkins/plugins/pipelinegraphview/utils/githubIssue274.jenkinsfile
Labels: enhancement

#279 Fixes icon issue for running job in pipeline
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/support/SvgStatus.tsx
Labels: bug

#280 Add Java 17 to build/test matrix
  Jenkinsfile
Labels: chore
