Repository jenkinsci/pipeline-graph-view-plugin, pull requests merged in 2023-02, with the labels that each got.

#212 Add links to previous and next builds to pipeline graph and console views
  src/main/frontend/pipeline-console-view/pipeline-console/main/pipeline-console.scss
  src/main/frontend/pipeline-graph-view/app.scss
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/AbstractPipelineViewAction.java
  src/main/resources/io/jenkins/plugins/pipelinegraphview/PipelineGraphViewAction/index.jelly
  src/main/resources/io/jenkins/plugins/pipelinegraphview/consoleview/PipelineConsoleViewAction/index.jelly
Labels: enhancement

#210 Add step logs to stage view - as expandable sections.
  package-lock.json
  package.json
  src/main/frontend/pipeline-console-view/pipeline-console/main/Ansi.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/ConsoleLine.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/ConsoleLogCard.spec.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/ConsoleLogCard.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/DataTreeView.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/PipelineConsole.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/PipelineConsoleModel.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/StageView.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/pipeline-console.scss
  src/main/java/io/jenkins/plugins/pipelinegraphview/consoleview/PipelineConsoleViewAction.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineStepApi.java
Labels: enhancement

#215 Tick 'Modern logs viewing' in Readme
  README.md
Labels: documentation

#219 Remove unused '.svg-icon' css class from Console.
  src/main/frontend/pipeline-console-view/pipeline-console/main/pipeline-console.scss
Labels: bug

#217 Add entrys to steps list for uncaught exceptions
  src/main/frontend/pipeline-console-view/pipeline-console/main/ConsoleLogCard.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/pipeline-console.scss
  src/main/java/io/jenkins/plugins/pipelinegraphview/consoleview/PipelineConsoleViewAction.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/FlowNodeWrapper.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineNodeUtil.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineStepApi.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineStepVisitor.java
  src/test/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineStepApiTest.java
  src/test/resources/io/jenkins/plugins/pipelinegraphview/utils/callsUnknownVariable.jenkinsfile
Labels: enhancement

#229 Add support for nested script stages.
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineNodeGraphVisitor.java
Labels: enhancement

#231 Remove `createGraph` API
  src/main/frontend/multi-pipeline-graph-view/multi-pipeline-graph/main/SingleRun.tsx
  src/main/java/io/jenkins/plugins/pipelinegraphview/multipipelinegraphview/MultiPipelineGraphViewAction.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/AbstractPipelineViewAction.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineGraphApi.java
  src/test/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineGraphApiTest.java
Labels: chore

#163 Buttons to Navigate between Graph and Console Views
  src/main/resources/io/jenkins/plugins/pipelinegraphview/PipelineGraphViewAction/index.jelly
  src/main/resources/io/jenkins/plugins/pipelinegraphview/consoleview/PipelineConsoleViewAction/index.jelly
Labels: enhancement

#230 Fix 'getConsoleOutput' + add tests
  src/main/frontend/pipeline-console-view/pipeline-console/main/ConsoleLogCard.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/PipelineConsole.tsx
  src/main/java/io/jenkins/plugins/pipelinegraphview/consoleview/PipelineConsoleViewAction.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineNodeUtil.java
  src/test/java/io/jenkins/plugins/pipelinegraphview/consoleview/PipelineConsoleViewActionTest.java
  src/test/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineNodeUtilTest.java
  src/test/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineStepApiTest.java
  src/test/resources/io/jenkins/plugins/pipelinegraphview/utils/helloWorldScriptedPipeline.jenkinsfile
  src/test/resources/io/jenkins/plugins/pipelinegraphview/utils/simpleError.jenkinsfile
Labels: bug

#232 Provide full text in tooltip of truncated labels
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/support/TruncatingLabel.tsx
Labels: enhancement
