Repository jenkinsci/pipeline-graph-view-plugin, pull requests merged in 2023-04, with the labels that each got.

#253 Add log following
  package-lock.json
  package.json
  src/main/frontend/common/Poller.tsx
  src/main/frontend/common/RestClient.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/ConsoleLogCard.spec.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/ConsoleLogCard.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/ConsoleLogStream.spec.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/ConsoleLogStream.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/DataTreeView.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/PipelineConsole.spec.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/PipelineConsole.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/PipelineConsoleModel.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/StageView.spec.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/StageView.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/TestData.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/pipeline-console.scss
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/PipelineGraphModel.tsx
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/support/StatusIcons.tsx
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/support/SvgStatus.tsx
  src/main/frontend/step-status/StepStatus.tsx
  src/main/java/io/jenkins/plugins/pipelinegraphview/consoleview/PipelineConsoleViewAction.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/AbstractPipelineViewAction.java
Labels: enhancement

#267 Use upstream Spotless configuration
  .mvn_exec_spotless
  pom.xml
  src/main/java/io/jenkins/plugins/pipelinegraphview/PipelineGraphDisplayURLProvider.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/PipelineGraphViewAction.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/PipelineGraphViewActionFactory.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/cards/Card.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/cards/RunDetailsCard.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/cards/RunDetailsItem.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/cards/items/CauseRunDetailsItem.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/cards/items/GitHubBranchSourceRunDetailsItems.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/cards/items/SCMRunDetailsItems.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/cards/items/TimingRunDetailsItems.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/consoleview/PipelineConsoleViewAction.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/consoleview/PipelineConsoleViewActionFactory.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/multipipelinegraphview/MultiPipelineGraphViewAction.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/multipipelinegraphview/MultiPipelineGraphViewActionFactory.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/multipipelinegraphview/PipelineRun.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/AbstractPipelineViewAction.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/BlueRun.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/FlowNodeWrapper.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/NodeRunStatus.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineGraph.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineGraphApi.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineNodeGraphVisitor.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineNodeUtil.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineStage.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineStageInternal.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineStep.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineStepApi.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineStepList.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineStepVisitor.java
  src/test/java/io/jenkins/plugins/pipelinegraphview/consoleview/PipelineConsoleViewActionTest.java
  src/test/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineGraphApiTest.java
  src/test/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineNodeUtilTest.java
  src/test/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineStepApiTest.java
  src/test/java/io/jenkins/plugins/pipelinegraphview/utils/TestUtils.java
Labels: chore

#273 Remove alpha warning
  README.md
Labels: documentation
