Repository jenkinsci/pipeline-graph-view-plugin, pull requests merged in 2023-03, with the labels that each got.

#235 Switch to renovate
  .github/renovate.json
  renovate.json
Labels: chore

#236 Adjust renovate config
  .github/renovate.json
Labels: chore

#233 New graph visitor
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/FlowNodeWrapper.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/NodeRunStatus.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineGraphApi.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineNodeGraphAdapter.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineNodeGraphVisitor.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineNodeTreeVisitor.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineNodeUtil.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineStepApi.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineStepVisitor.java
  src/test/java/io/jenkins/plugins/pipelinegraphview/consoleview/PipelineConsoleViewActionTest.java
  src/test/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineGraphApiTest.java
  src/test/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineNodeUtilTest.java
  src/test/java/io/jenkins/plugins/pipelinegraphview/utils/TestUtils.java
  src/test/resources/io/jenkins/plugins/pipelinegraphview/utils/nestedDeclarativeParallel.jenkinsfile
  src/test/resources/io/jenkins/plugins/pipelinegraphview/utils/nestedSciptedParallel.jenkinsfile
Labels: enhancement

#223 Use babel-loader to enable code-splitting of bundles
  .bablerc.js
  package-lock.json
  package.json
  src/main/frontend/pipeline-console-view/app.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/ConsoleLogCard.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/DataTreeView.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/PipelineConsole.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/PipelineConsoleModel.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/pipeline-console.scss
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/index.ts
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/support/StatusIcons.tsx
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/support/SvgStatus.tsx
  src/main/frontend/step-status/StepStatus.tsx
  webpack.config.js
Labels: enhancement

#247 Fix Node SvgStatus rendering
  src/main/frontend/pipeline-console-view/pipeline-console/main/PipelineConsoleModel.tsx
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/support/SvgStatus.tsx
Labels: bug

#237 Progressive log text
  src/main/frontend/pipeline-console-view/pipeline-console/main/ConsoleLogCard.spec.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/ConsoleLogCard.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/DataTreeView.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/PipelineConsole.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/PipelineConsoleModel.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/StageView.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/pipeline-console.scss
Labels: enhancement

#250 Revert "New graph visitor"
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/FlowNodeWrapper.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/NodeRunStatus.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineGraphApi.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineNodeGraphAdapter.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineNodeGraphVisitor.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineNodeTreeVisitor.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineNodeUtil.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineStepApi.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineStepVisitor.java
  src/test/java/io/jenkins/plugins/pipelinegraphview/consoleview/PipelineConsoleViewActionTest.java
  src/test/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineGraphApiTest.java
  src/test/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineNodeUtilTest.java
  src/test/java/io/jenkins/plugins/pipelinegraphview/utils/TestUtils.java
  src/test/resources/io/jenkins/plugins/pipelinegraphview/utils/nestedDeclarativeParallel.jenkinsfile
  src/test/resources/io/jenkins/plugins/pipelinegraphview/utils/nestedSciptedParallel.jenkinsfile
Labels: bug

#257 Update JavaScript formatting
  src/main/frontend/pipeline-console-view/pipeline-console/main/ConsoleLogCard.spec.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/ConsoleLogCard.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/PipelineConsole.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/PipelineConsoleModel.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/StageView.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/pipeline-console.scss
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/support/SvgStatus.tsx
Labels: chore

#256 Java 11 in contributing guide
  CONTRIBUTING.md
Labels: documentation

#258 Use latest parent pom and plugin bom
  pom.xml
Labels: dependencies
