Repository jenkinsci/pipeline-graph-view-plugin, pull requests merged in 2023-08, with the labels that each got.

#291 Test on Java 21
  Jenkinsfile
Labels: chore

#293 Allow PipelineGraphDisplayURLProvider to activate by default, preserve direct tests/artifacts/changes links, and do not try to handle non-Pipeline builds
  pom.xml
  src/main/java/io/jenkins/plugins/pipelinegraphview/PipelineGraphDisplayURLProvider.java
Labels: enhancement

#294 Make package-lock.json git clean
  package-lock.json
Labels: skip-changelog
