Repository jenkinsci/pipeline-graph-view-plugin, pull requests merged in 2024-09, with the labels that each got.

#498 Fix PCT Test
  src/main/webapp/js/build.js
Labels: developer

#503 Improve performance for large pipeline graphs
  src/main/java/io/jenkins/plugins/pipelinegraphview/treescanner/NodeRelationship.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/treescanner/NodeRelationshipFinder.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/treescanner/ParallelBlockRelationship.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/treescanner/PipelineNodeGraphAdapter.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/treescanner/PipelineNodeTreeScanner.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/FlowNodeWrapper.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/legacy/PipelineNodeGraphVisitor.java
Labels: enhancement

#497 Use '.jenkins-card' for cards
  pom.xml
  src/main/frontend/multi-pipeline-graph-view/multi-pipeline-graph/styles/variables.scss
  src/main/frontend/pipeline-console-view/pipeline-console/main/pipeline-console.scss
  src/main/frontend/pipeline-graph-view/_cards.scss
  src/main/frontend/pipeline-graph-view/app.scss
  src/main/frontend/pipeline-graph-view/pipeline-graph/styles/main.scss
  src/main/frontend/pipeline-graph-view/pipeline-graph/styles/variables.scss
  src/main/resources/io/jenkins/plugins/pipelinegraphview/PipelineGraphViewAction/index.jelly
  src/main/resources/lib/pipeline-graph-view/card.jelly
Labels: enhancement

#514 Update lock file
  package-lock.json
Labels: chore
