Repository jenkinsci/pipeline-graph-view-plugin, pull requests merged in 2024-04, with the labels that each got.

#377 Return root stages if they have child steps.
  src/main/java/io/jenkins/plugins/pipelinegraphview/treescanner/PipelineNodeTreeScanner.java
Labels: bug

#371 Improve the height calculation of the ConsoleLogStream component
  src/main/frontend/pipeline-console-view/pipeline-console/main/ConsoleLine.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/ConsoleLogCard.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/ConsoleLogModal.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/ConsoleLogStream.tsx
Labels: enhancement

#380 Revert "Return root stages if they have child steps."
  src/main/java/io/jenkins/plugins/pipelinegraphview/treescanner/PipelineNodeTreeScanner.java
Labels: bug

#383 Use NodeRunStatus(FlowNode) to determine the status for StepNodes
  src/main/java/io/jenkins/plugins/pipelinegraphview/treescanner/NodeRelationship.java
Labels: bug

#386 Fix failing unit test
  src/main/frontend/pipeline-console-view/pipeline-console/main/ConsoleLogStream.spec.tsx
Labels: test

#387 Small improvements to branch labels
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/support/labels.tsx
  src/main/frontend/pipeline-graph-view/pipeline-graph/styles/main.scss
Labels: enhancement

#389 Fix display for ANSI colors
  src/main/frontend/pipeline-console-view/pipeline-console/main/pipeline-console.scss
Labels: bug

#392 Update plugin POM and BOM
  .github/release-drafter.yml
  .github/workflows/cd.yaml
  .mvn/extensions.xml
  pom.xml
  src/main/java/io/jenkins/plugins/pipelinegraphview/treescanner/PipelineNodeTreeScanner.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/legacy/PipelineNodeGraphVisitor.java
  src/test/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineStepApiLegacyTest.java
  src/test/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineStepApiTest.java
Labels: developer

#394 Fix test flake preventing BOM release
  src/test/resources/io/jenkins/plugins/pipelinegraphview/utils/complexParallelSmokes.jenkinsfile
Labels: developer

#395 Backport of PCT fixes to 2.426.x line
  .github/release-drafter.yml
  .github/workflows/cd.yaml
  .mvn/extensions.xml
  pom.xml
  src/main/frontend/pipeline-console-view/pipeline-console/main/CloseIcon.tsx
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineNodeGraphVisitor.java
  src/test/resources/io/jenkins/plugins/pipelinegraphview/utils/complexParallelSmokes.jenkinsfile
Labels: chore
