Repository jenkinsci/pipeline-graph-view-plugin, pull requests merged in 2024-02, with the labels that each got.

#332 feat: exclude line numbers from text selection/copy
  src/main/frontend/pipeline-console-view/pipeline-console/main/pipeline-console.scss
Labels: enhancement

#333 Add tooltips to console log viewing
  package-lock.json
  package.json
  src/main/frontend/pipeline-console-view/pipeline-console/main/ConsoleLogCard.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/pipeline-console.scss
Labels: enhancement

#334 Add background to console log modal
  src/main/frontend/pipeline-console-view/pipeline-console/main/ConsoleLogModal.tsx
Labels: bug

#336 Remove BO in docs
  docs/images/action.png
Labels: chore

#337 Matrix label rework
  src/main/frontend/pipeline-console-view/pipeline-console/main/CloseIcon.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/ConsoleLogCard.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/pipeline-console.scss
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/support/convertLabelToTooltip.spec.tsx
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/support/convertLabelToTooltip.tsx
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/support/labels.tsx
  src/main/frontend/pipeline-graph-view/pipeline-graph/styles/PipelineGraphWidget.scss
Labels: enhancement

#340 Fix awkward overflow text breaks in id column of multi-pipeline-graph-view
  src/main/frontend/multi-pipeline-graph-view/app.scss
Labels: enhancement

#345 Use --accent-color for running steps in the Console View
  src/main/frontend/pipeline-console-view/pipeline-console/main/pipeline-console.scss
Labels: enhancement
