Repository jenkinsci/pipeline-graph-view-plugin, pull requests merged in 2024-05, with the labels that each got.

#397 Tweak renovate config
  .github/renovate.json
Labels: chore

#424 Fix renovate config
  .github/renovate.json
Labels: chore

#425 Fix classic console and View as plain text buttons missing in console view overflow
  pom.xml
  src/main/resources/io/jenkins/plugins/pipelinegraphview/consoleview/PipelineConsoleViewAction/index.jelly
Labels: bug

#427 Tweak renovate config
  .github/renovate.json
Labels: chore

#428 Fix tests
  package-lock.json
  package.json
  src/main/frontend/pipeline-console-view/pipeline-console/main/ConsoleLogCard.spec.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/ConsoleLogStream.spec.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/PipelineConsole.spec.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/StageView.spec.tsx
  tsconfig.json
Labels: test

#429 Remove unused html-react-parser dependency
  package-lock.json
  package.json
Labels: chore

#438 Use LTS baseline and ensure same bom version
  pom.xml
Labels: dependencies
