Repository jenkinsci/pipeline-graph-view-plugin, pull requests merged in 2024-10, with the labels that each got.

#522 Fix Prettier violations
  src/main/frontend/common/RestClient.tsx
  src/main/frontend/multi-pipeline-graph-view/multi-pipeline-graph/main/support/startPollingRunsStatus.ts
  src/main/frontend/multi-pipeline-graph-view/multi-pipeline-graph/styles/variables.scss
  src/main/frontend/pipeline-console-view/app.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/Ansi.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/ConsoleLine.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/ConsoleLogCard.spec.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/ConsoleLogCard.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/ConsoleLogModal.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/ConsoleLogStream.spec.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/ConsoleLogStream.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/DataTreeView.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/PipelineConsole.spec.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/PipelineConsole.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/StageView.spec.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/TestData.tsx
  src/main/frontend/pipeline-graph-view/_cards.scss
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/PipelineGraph.tsx
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/PipelineGraphLayout.spec.ts
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/PipelineGraphLayout.ts
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/support/StatusIcons.tsx
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/support/SvgSpinner.tsx
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/support/SvgStatus.tsx
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/support/TruncatingLabel.tsx
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/support/connections.tsx
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/support/convertLabelToTooltip.spec.tsx
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/support/convertLabelToTooltip.tsx
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/support/labels.tsx
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/support/nodes.tsx
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/support/startPollingPipelineStatus.ts
  src/main/frontend/pipeline-graph-view/pipeline-graph/styles/variables.scss
  src/main/frontend/step-status/StepStatus.tsx
Labels: internal

#523 Set `Content-Type` header for console logs
  src/main/java/io/jenkins/plugins/pipelinegraphview/consoleview/PipelineConsoleViewAction.java
Labels: bug

#545 Stop using deprecated `getCompressedWriter`
  src/main/java/io/jenkins/plugins/pipelinegraphview/consoleview/PipelineConsoleViewAction.java
Labels: developer, internal

#546 Add baseline variable
  pom.xml
Labels: chore

#547 Update `package-lock.json`
  package-lock.json
Labels: skip-changelog
