Repository jenkinsci/pipeline-graph-view-plugin, pull requests merged in 2024-03, with the labels that each got.

#347 Refresh the Console View Step Header Cards
  src/main/frontend/pipeline-console-view/pipeline-console/main/ConsoleLogCard.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/ConsoleLogModal.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/pipeline-console.scss
  src/main/frontend/step-status/StepStatus.tsx
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineStepApi.java
  src/test/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineStepApiTest.java
Labels: enhancement

#351 Fix incorrect step result when referencing an ErrorAction
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/BlueRun.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/NodeRunStatus.java
Labels: bug

#355 Pull log text if ConsoleLogCard starts expanded.
  src/main/frontend/pipeline-console-view/pipeline-console/main/ConsoleLogCard.spec.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/ConsoleLogCard.tsx
Labels: bug

#356 Workaround slow flowgraph to fix flakey test
  .editorconfig
  src/test/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineStepApiTest.java
Labels: test

#359 Handle skipped stages in parallel branches
  pom.xml
  src/main/java/io/jenkins/plugins/pipelinegraphview/treescanner/ParallelBlockRelationship.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/NodeRunStatus.java
  src/test/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineGraphApiTest.java
  src/test/resources/io/jenkins/plugins/pipelinegraphview/utils/gh_358_parallelStagesMarkedAsSkipped.jenkinsfile
Labels: bug

#364 Improve reliablity of finding 'after' nodes.
  src/main/java/io/jenkins/plugins/pipelinegraphview/treescanner/NodeRelationship.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/treescanner/NodeRelationshipFinder.java
  src/test/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineStepApiTest.java
  src/test/resources/io/jenkins/plugins/pipelinegraphview/utils/stepBlockInSteps.jenkinsfile
Labels: enhancement

#373 Add UpstreamCause to RunDetailsCard on pipeline overview graph
  src/main/java/io/jenkins/plugins/pipelinegraphview/PipelineGraphViewAction.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/cards/items/UpstreamCauseRunDetailsItem.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/cards/items/UserIdCauseRunDetailsItem.java
Labels: enhancement
