Repository jenkinsci/pipeline-graph-view-plugin, pull requests merged in 2025-05, with the labels that each got.

#699 Remove the @messageformat/core library
  package-lock.json
  package.json
  src/main/frontend/common/i18n/choice-formatter.spec.ts
  src/main/frontend/common/i18n/choice-formatter.ts
  src/main/frontend/common/i18n/index.ts
  src/main/frontend/common/i18n/message-format.spec.ts
  src/main/frontend/common/i18n/message-format.ts
  src/main/frontend/common/i18n/messages.ts
Labels: enhancement

#700 Setup crowdin for receiving translation through localisation platform
  .github/workflows/crowdin.yml
  crowdin.yml
Labels: chore

#702 Propagate locale throughout the application
  src/main/frontend/common/i18n/i18n-provider.tsx
  src/main/frontend/common/i18n/index.ts
  src/main/frontend/common/i18n/locale-provider.tsx
  src/main/frontend/multi-pipeline-graph-view/app.tsx
  src/main/frontend/multi-pipeline-graph-view/multi-pipeline-graph/main/MultiPipelineGraph.tsx
  src/main/frontend/pipeline-console-view/app.tsx
Labels: bug

#708 Update crowdin.yml
  .github/workflows/crowdin.yml
Labels: chore

#709 Optimize interface for mobile
  src/main/frontend/pipeline-console-view/pipeline-console/main/PipelineConsole.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/StageNodeLink.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/components/stages-customization.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/providers/user-preference-provider.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/split-view.scss
  src/main/frontend/pipeline-console-view/pipeline-console/main/stage-details.tsx
Labels: enhancement

#711 Fix resizing panels
  src/main/frontend/pipeline-console-view/pipeline-console/main/split-view.scss
Labels: bugfix

#706 Don't buffer logs in memory when viewing log as plain text
  pom.xml
  src/main/java/io/jenkins/plugins/pipelinegraphview/consoleview/PipelineConsoleViewAction.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineNodeUtil.java
  src/test/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineNodeUtilTest.java
Labels: bug

#719 Tweaks to crowdin
  .github/workflows/crowdin.yml
Labels: chore

#725 Add tests results to info bar in console
  pom.xml
  src/main/java/io/jenkins/plugins/pipelinegraphview/cards/RunDetailsItem.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/cards/items/TestResultRunDetailsItems.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/consoleview/PipelineConsoleViewAction.java
  src/main/resources/io/jenkins/plugins/pipelinegraphview/Messages.properties
  src/main/resources/io/jenkins/plugins/pipelinegraphview/consoleview/PipelineConsoleViewAction/index.jelly
Labels: enhancement

#728 Add artifacts link
  src/main/java/io/jenkins/plugins/pipelinegraphview/cards/items/ArtifactRunDetailsItem.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/cards/items/TestResultRunDetailsItem.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/consoleview/PipelineConsoleViewAction.java
  src/main/resources/io/jenkins/plugins/pipelinegraphview/Messages.properties
Labels: enhancement

#726 Fix overflow on matrix build / nested parallel
  src/main/frontend/pipeline-console-view/pipeline-console/main/split-view.scss
  src/main/frontend/pipeline-console-view/pipeline-console/main/split-view.tsx
Labels: bugfix

#733 Make overflow on sidebar hidden
  src/main/frontend/pipeline-console-view/pipeline-console/main/pipeline-console.scss
Labels: bug

#734 Add i18n support for run detail cards
  src/main/java/io/jenkins/plugins/pipelinegraphview/cards/items/TestResultRunDetailsItem.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/cards/items/TimingRunDetailsItems.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/cards/items/UpstreamCauseRunDetailsItem.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/cards/items/UserIdCauseRunDetailsItem.java
  src/main/resources/io/jenkins/plugins/pipelinegraphview/Messages.properties
Labels: enhancement

#740 Simplify Jelly for run detail card items
  src/main/java/io/jenkins/plugins/pipelinegraphview/cards/RunDetailsCard.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/cards/RunDetailsItem.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/cards/items/ArtifactRunDetailsItem.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/cards/items/GitHubBranchSourceRunDetailsItems.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/cards/items/SCMRunDetailsItems.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/cards/items/TestResultRunDetailsItem.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/cards/items/TimingRunDetailsItems.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/cards/items/UpstreamCauseRunDetailsItem.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/cards/items/UserIdCauseRunDetailsItem.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/consoleview/PipelineConsoleViewAction.java
  src/main/resources/io/jenkins/plugins/pipelinegraphview/cards/RunDetailsItem/ItemContent/LinkContent/description.jelly
  src/main/resources/io/jenkins/plugins/pipelinegraphview/cards/RunDetailsItem/ItemContent/PlainContent/description.jelly
  src/main/resources/io/jenkins/plugins/pipelinegraphview/cards/RunDetailsItem/RunDetail/description.jelly
  src/main/resources/io/jenkins/plugins/pipelinegraphview/cards/RunDetailsItem/Separator/description.jelly
  src/main/resources/io/jenkins/plugins/pipelinegraphview/consoleview/PipelineConsoleViewAction/index.jelly
Labels: chore

#742 Set a text/plain content-type on log text
  src/main/java/io/jenkins/plugins/pipelinegraphview/consoleview/PipelineConsoleViewAction.java
Labels: enhancement

#746 Fix NPE when no cause can be identified
  src/main/java/io/jenkins/plugins/pipelinegraphview/cards/items/UpstreamCauseRunDetailsItem.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/cards/items/UserIdCauseRunDetailsItem.java
  src/test/java/io/jenkins/plugins/pipelinegraphview/cards/items/UpstreamCauseRunDetailsItemTest.java
  src/test/java/io/jenkins/plugins/pipelinegraphview/cards/items/UserIdCauseRunDetailsItemTest.java
Labels: bug

#749 Fix scroll up/down controls overlaying full screen graph
  src/main/frontend/pipeline-console-view/pipeline-console/main/components/stages.scss
Labels: bugfix

#748 Rename Pipeline Console to Pipeline Overview
  src/main/frontend/common/RestClient.tsx
  src/main/java/io/jenkins/plugins/pipelinegraphview/PipelineGraphDisplayURLProvider.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/consoleview/PipelineConsoleViewAction.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/AbstractPipelineViewAction.java
  src/main/resources/io/jenkins/plugins/pipelinegraphview/consoleview/PipelineConsoleViewAction/index.jelly
Labels: enhancement

#751 Fix node URL
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineStage.java
Labels: bugfix

#754 refactor: convert pipeline stages tree to use a semantic tree list structure
  src/main/frontend/pipeline-console-view/pipeline-console/main/DataTreeView.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/data-tree-view.scss
  src/main/frontend/pipeline-console-view/pipeline-console/main/pipeline-console.scss
Labels: developer

#731 Playwright E2E Smoke Test
  src/main/frontend/common/components/filter.tsx
  src/main/frontend/common/components/status-icon.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/ConsoleLogStream.tsx
  src/test/java/io/jenkins/plugins/pipelinegraphview/PipelineGraphViewTest.java
  src/test/java/io/jenkins/plugins/pipelinegraphview/playwright/JenkinsPage.java
  src/test/java/io/jenkins/plugins/pipelinegraphview/playwright/ManageAppearancePage.java
  src/test/java/io/jenkins/plugins/pipelinegraphview/playwright/OverviewTree.java
  src/test/java/io/jenkins/plugins/pipelinegraphview/playwright/PipelineBuildPage.java
  src/test/java/io/jenkins/plugins/pipelinegraphview/playwright/PipelineConsole.java
  src/test/java/io/jenkins/plugins/pipelinegraphview/playwright/PipelineGraph.java
  src/test/java/io/jenkins/plugins/pipelinegraphview/playwright/PipelineJobPage.java
  src/test/java/io/jenkins/plugins/pipelinegraphview/playwright/PipelineOverviewPage.java
  src/test/java/io/jenkins/plugins/pipelinegraphview/playwright/PlaywrightConfig.java
  src/test/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineGraphApiTest.java
  src/test/java/io/jenkins/plugins/pipelinegraphview/utils/TestUtils.java
  src/test/resources/io/jenkins/plugins/pipelinegraphview/utils/nestedScriptedParallel.jenkinsfile
  src/test/resources/io/jenkins/plugins/pipelinegraphview/utils/smokeTest.jenkinsfile
Labels: test

#743 Add changes link
  src/main/java/io/jenkins/plugins/pipelinegraphview/cards/items/ChangesRunDetailsItem.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/consoleview/PipelineConsoleViewAction.java
  src/main/resources/io/jenkins/plugins/pipelinegraphview/Messages.properties
  src/test/java/io/jenkins/plugins/pipelinegraphview/cards/items/ChangesRunDetailsItemTest.java
  src/test/resources/io/jenkins/plugins/pipelinegraphview/utils/singleStagePipelineWithSCM.jenkinsfile
Labels: enhancement

#762 fix: log anchoring with small stage logs
  src/main/frontend/pipeline-console-view/pipeline-console/main/ConsoleLogStream.tsx
Labels: bug

#761 chore(ci): remove corrupted channel writes in build logs
  pom.xml
Labels: chore

#759 Add pseudo-stage if no stage created yet
  src/main/frontend/common/RestClient.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/DataTreeView.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/NoStageStepsFallback.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/PipelineConsole.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/stage-details.tsx
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/PipelineGraphLayout.ts
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/PipelineGraphModel.tsx
  src/main/java/io/jenkins/plugins/pipelinegraphview/consoleview/PipelineConsoleViewAction.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/treescanner/PipelineNodeTreeScanner.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/FlowNodeWrapper.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineGraphApi.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineStage.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineStageInternal.java
  src/main/resources/io/jenkins/plugins/pipelinegraphview/Messages.properties
  src/test/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineGraphApiTest.java
  src/test/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineStepApiTest.java
  src/test/resources/io/jenkins/plugins/pipelinegraphview/utils/noStage.jenkinsfile
Labels: enhancement

#765 Use the result of a WarningAction set on a branch node instead of the calculated status
  src/main/java/io/jenkins/plugins/pipelinegraphview/treescanner/ParallelBlockRelationship.java
  src/test/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineGraphApiTest.java
  src/test/resources/io/jenkins/plugins/pipelinegraphview/utils/gh764_branchResult.jenkinsfile
Labels: enhancement

#766 Add cancel button to pipeline overview
  pom.xml
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/AbstractPipelineViewAction.java
  src/main/resources/io/jenkins/plugins/pipelinegraphview/Messages.properties
  src/main/resources/io/jenkins/plugins/pipelinegraphview/consoleview/PipelineConsoleViewAction/index.jelly
  src/main/resources/io/jenkins/plugins/pipelinegraphview/consoleview/PipelineConsoleViewAction/index.properties
  src/main/webapp/js/build.js
  src/test/java/io/jenkins/plugins/pipelinegraphview/PipelineGraphViewCancelTest.java
  src/test/java/io/jenkins/plugins/pipelinegraphview/playwright/PipelineOverviewPage.java
  src/test/resources/io/jenkins/plugins/pipelinegraphview/configure-appearance.yml
  src/test/resources/io/jenkins/plugins/pipelinegraphview/utils/indefiniteWait.jenkinsfile
Labels: enhancement

#773 Extract strings to properties files for crowdin
  src/main/resources/io/jenkins/plugins/pipelinegraphview/PipelineGraphViewConfiguration/config.properties
  src/main/resources/io/jenkins/plugins/pipelinegraphview/consoleview/PipelineConsoleViewAction/index.properties
  src/main/resources/io/jenkins/plugins/pipelinegraphview/multipipelinegraphview/MultiPipelineGraphViewAction/index.properties
Labels: chore

#774 Use user avatars for User causes
  src/main/java/io/jenkins/plugins/pipelinegraphview/cards/items/UserIdCauseRunDetailsItem.java
  src/main/resources/io/jenkins/plugins/pipelinegraphview/cards/RunDetailsItem/RunDetail/description.jelly
  src/main/webapp/js/style.css
  src/test/java/io/jenkins/plugins/pipelinegraphview/cards/items/UserIdCauseRunDetailsItemTest.java
Labels: enhancement

#776 Use notification bar to report result of rebuild and cancel button actions
  eslint.config.js
  src/main/resources/io/jenkins/plugins/pipelinegraphview/consoleview/PipelineConsoleViewAction/index.jelly
  src/main/resources/io/jenkins/plugins/pipelinegraphview/consoleview/PipelineConsoleViewAction/index.properties
  src/main/webapp/js/build.js
Labels: enhancement

#777 Move Configure button to overflow dropdown
  src/main/frontend/pipeline-console-view/pipeline-console/main/PipelineConsole.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/symbols.tsx
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/AbstractPipelineViewAction.java
  src/main/resources/io/jenkins/plugins/pipelinegraphview/consoleview/PipelineConsoleViewAction/index.jelly
  src/test/java/io/jenkins/plugins/pipelinegraphview/PipelineGraphViewConfigureTest.java
  src/test/java/io/jenkins/plugins/pipelinegraphview/playwright/PipelineOverviewPage.java
Labels: enhancement

#786 Test coverage for input step
  src/test/java/io/jenkins/plugins/pipelinegraphview/consoleview/PipelineConsoleViewInputTest.java
  src/test/java/io/jenkins/plugins/pipelinegraphview/playwright/InputPage.java
  src/test/java/io/jenkins/plugins/pipelinegraphview/playwright/OverviewTree.java
  src/test/java/io/jenkins/plugins/pipelinegraphview/playwright/PipelineOverviewPage.java
  src/test/resources/io/jenkins/plugins/pipelinegraphview/utils/input-with-parameters.jenkinsfile
  src/test/resources/io/jenkins/plugins/pipelinegraphview/utils/input.jenkinsfile
Labels: test

#790 Add changes count to Stages card
  src/main/frontend/common/i18n/messages.ts
  src/main/frontend/multi-pipeline-graph-view/multi-pipeline-graph/main/MultiPipelineGraphModel.ts
  src/main/frontend/multi-pipeline-graph-view/multi-pipeline-graph/main/SingleRun.tsx
  src/main/frontend/multi-pipeline-graph-view/multi-pipeline-graph/main/single-run.scss
  src/main/java/io/jenkins/plugins/pipelinegraphview/cards/items/ChangesRunDetailsItem.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/multipipelinegraphview/PipelineRun.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/ChangesUtil.java
  src/main/resources/io/jenkins/plugins/pipelinegraphview/Messages.properties
Labels: enhancement

#796 Hide cancel button when pipeline completes
  src/main/webapp/js/build.js
  src/test/java/io/jenkins/plugins/pipelinegraphview/PipelineGraphViewCancelTest.java
Labels: bug

#802 Don't escape commit messages in changes card tooltip
  src/main/java/io/jenkins/plugins/pipelinegraphview/cards/items/ChangesRunDetailsItem.java
Labels: bug

#798 Don't select first unsuccessful step when the pipeline is running
  src/main/frontend/pipeline-console-view/pipeline-console/main/hooks/use-steps-poller.ts
  src/test/java/io/jenkins/plugins/pipelinegraphview/PipelineGraphViewTest.java
  src/test/resources/io/jenkins/plugins/pipelinegraphview/utils/gh797_errorAndContinue.jenkinsfile
  src/test/resources/io/jenkins/plugins/pipelinegraphview/utils/gh797_errorAndContinueWithWait.jenkinsfile
Labels: bug

#803 Migrate pipeline-graph-analysis-plugin implementations
  pom.xml
  src/main/java/io/jenkins/plugins/pipelinegraphview/analysis/GenericStatus.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/analysis/StageChunkFinder.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/analysis/StageStatus.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/analysis/StatusAndTiming.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/analysis/TimingInfo.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/treescanner/NodeRelationship.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/treescanner/ParallelBlockRelationship.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/treescanner/PipelineNodeTreeScanner.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/AbstractPipelineNode.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/FlowNodeWrapper.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/NodeRunStatus.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineStage.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineStageInternal.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineStep.java
  src/test/java/io/jenkins/plugins/pipelinegraphview/analysis/StageTest.java
  src/test/java/io/jenkins/plugins/pipelinegraphview/analysis/StatusAndTimingTest.java
Labels: chore

#807 Disable test that fails in PCT
  src/test/java/io/jenkins/plugins/pipelinegraphview/consoleview/PipelineConsoleViewInputTest.java
Labels: developer
