Repository jenkinsci/pipeline-graph-view-plugin, pull requests merged in 2025-04, with the labels that each got.

#614 Update app bar build icon
  src/main/resources/io/jenkins/plugins/pipelinegraphview/PipelineGraphViewAction/index.jelly
  src/main/resources/io/jenkins/plugins/pipelinegraphview/consoleview/PipelineConsoleViewAction/index.jelly
Labels: enhancement

#613 Revamp the tree view
  .bablerc.js
  package-lock.json
  package.json
  src/main/frontend/pipeline-console-view/pipeline-console/main/DataTreeView.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/PipelineConsole.spec.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/PipelineConsole.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/SplitView.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/data-tree-view.scss
  src/main/frontend/pipeline-console-view/pipeline-console/main/pipeline-console.scss
  src/main/frontend/pipeline-console-view/pipeline-console/main/split-view.scss
  src/main/frontend/step-status/StepStatus.tsx
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/AbstractPipelineNode.java
Labels: enhancement

#617 Use the result of a WarningAction set on a stage node instead of computing the chunk status
  src/main/java/io/jenkins/plugins/pipelinegraphview/treescanner/NodeRelationship.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/legacy/PipelineNodeGraphVisitor.java
  src/test/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineGraphApiLegacyTest.java
  src/test/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineGraphApiTest.java
  src/test/java/io/jenkins/plugins/pipelinegraphview/utils/TestUtils.java
  src/test/resources/io/jenkins/plugins/pipelinegraphview/utils/gh616_stageResult.jenkinsfile
Labels: enhancement

#584 Fix PipelineNodeUtil categorization of steps, stages and parallel branches
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/FlowNodeWrapper.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineNodeUtil.java
  src/test/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineNodeUtilTest.java
  src/test/resources/io/jenkins/plugins/pipelinegraphview/utils/gh583_stages.jenkinsfile
Labels: enhancement

#620 Update stage buttons to be links
  src/main/frontend/pipeline-console-view/pipeline-console/main/DataTreeView.tsx
Labels: enhancement

#625 Remove "environment reset due to Prototype"
  src/main/frontend/common/reset-environment.ts
  src/main/frontend/multi-pipeline-graph-view/index.tsx
  src/main/frontend/pipeline-console-view/index.tsx
  src/main/frontend/pipeline-graph-view/index.tsx
Labels: enhancement

#628 Update build status icon on complete
  src/main/java/io/jenkins/plugins/pipelinegraphview/PipelineGraphViewAction.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/consoleview/PipelineConsoleViewAction.java
  src/main/resources/io/jenkins/plugins/pipelinegraphview/PipelineGraphViewAction/index.jelly
  src/main/resources/io/jenkins/plugins/pipelinegraphview/consoleview/PipelineConsoleViewAction/index.jelly
Labels: bug

#626 Display information based off the previous run
  src/main/frontend/common/RestClient.tsx
  src/main/frontend/common/components/status-icon.scss
  src/main/frontend/common/components/status-icon.tsx
  src/main/frontend/common/tree-api.ts
  src/main/frontend/common/utils/run-estimator.spec.ts
  src/main/frontend/common/utils/run-estimator.ts
  src/main/frontend/common/utils/stage-merge.spec.ts
  src/main/frontend/common/utils/stage-merge.ts
  src/main/frontend/common/utils/timings.spec.ts
  src/main/frontend/common/utils/timings.ts
  src/main/frontend/multi-pipeline-graph-view/multi-pipeline-graph/main/MultiPipelineGraph.tsx
  src/main/frontend/multi-pipeline-graph-view/multi-pipeline-graph/main/SingleRun.tsx
  src/main/frontend/multi-pipeline-graph-view/multi-pipeline-graph/main/support/startPollingRunsStatus.ts
  src/main/frontend/pipeline-console-view/pipeline-console/main/ConsoleLogCard.spec.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/ConsoleLogCard.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/ConsoleLogModal.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/ConsoleLogStream.spec.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/DataTreeView.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/PipelineConsole.spec.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/PipelineConsole.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/PipelineConsoleModel.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/StageView.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/TestData.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/pipeline-console.scss
  src/main/frontend/pipeline-graph-view/app.tsx
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/PipelineGraph.tsx
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/PipelineGraphLayout.spec.ts
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/PipelineGraphLayout.ts
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/PipelineGraphModel.tsx
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/support/StatusIcons.tsx
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/support/labels.tsx
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/support/nodes.tsx
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/support/startPollingPipelineStatus.ts
  src/main/frontend/pipeline-graph-view/pipeline-graph/styles/PipelineGraphWidget.scss
  src/main/frontend/status-icon/StatusIcon.tsx
  src/main/frontend/step-status/StepStatus.tsx
  src/main/java/io/jenkins/plugins/pipelinegraphview/multipipelinegraphview/MultiPipelineGraphViewAction.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/AbstractPipelineNode.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/AbstractPipelineViewAction.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineGraphApi.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineStage.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineStageInternal.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineStep.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineStepApi.java
  src/main/resources/io/jenkins/plugins/pipelinegraphview/PipelineGraphViewAction/index.jelly
  src/main/resources/io/jenkins/plugins/pipelinegraphview/PipelineGraphViewAction/summary.jelly
  src/main/resources/io/jenkins/plugins/pipelinegraphview/multipipelinegraphview/MultiPipelineGraphViewAction/index.jelly
  src/main/resources/io/jenkins/plugins/pipelinegraphview/multipipelinegraphview/MultiPipelineGraphViewAction/jobMain.jelly
  src/test/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineGraphApiLegacyTest.java
Labels: enhancement

#635 Improve app bar appearance
  src/main/frontend/pipeline-console-view/pipeline-console/main/pipeline-console.scss
  src/main/frontend/pipeline-graph-view/app.scss
  src/main/resources/io/jenkins/plugins/pipelinegraphview/PipelineGraphViewAction/index.jelly
  src/main/resources/io/jenkins/plugins/pipelinegraphview/PipelineGraphViewAction/summary.jelly
  src/main/resources/io/jenkins/plugins/pipelinegraphview/consoleview/PipelineConsoleViewAction/index.jelly
  src/main/resources/io/jenkins/plugins/pipelinegraphview/multipipelinegraphview/MultiPipelineGraphViewAction/index.jelly
  src/main/resources/io/jenkins/plugins/pipelinegraphview/multipipelinegraphview/MultiPipelineGraphViewAction/jobMain.jelly
  src/main/resources/lib/pipeline-graph-view/symbols.jelly
  src/main/webapp/js/style.css
Labels: enhancement

#636 Introduce a State enum for the Pipeline/Stage representations
  src/main/frontend/pipeline-console-view/pipeline-console/main/PipelineConsoleModel.tsx
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/PipelineGraphModel.tsx
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/support/nodes.tsx
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/AbstractPipelineNode.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineGraphApi.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineStage.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineStageInternal.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineState.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineStep.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineStepApi.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/TreeBuilder.java
  src/test/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineStateTest.java
Labels: internal

#640 Fix some elements shrinking when they shouldn't
  src/main/frontend/common/components/status-icon.scss
  src/main/frontend/pipeline-console-view/pipeline-console/main/console-log-card.scss
  src/main/frontend/pipeline-console-view/pipeline-console/main/stage-details.scss
Labels: bugfix

#641 Fix order of names in steps
  src/main/frontend/pipeline-console-view/pipeline-console/main/ConsoleLogCard.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/console-log-card.scss
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineStepApi.java
  src/test/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineStepApiLegacyTest.java
  src/test/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineStepApiTest.java
Labels: enhancement

#642 Remove unused dependencies
  package-lock.json
  package.json
Labels: dependencies

#644 Use Jenkins reporting for test failures
  pom.xml
Labels: internal

#631 Introduce i18n API for the frontend
  package-lock.json
  package.json
  src/main/frontend/common/RestClient.tsx
  src/main/frontend/common/i18n/choice-formatter.spec.ts
  src/main/frontend/common/i18n/choice-formatter.ts
  src/main/frontend/common/i18n/i18n-provider.tsx
  src/main/frontend/common/i18n/translations.spec.ts
  src/main/frontend/common/i18n/translations.ts
  src/main/frontend/common/utils/timings.spec.ts
  src/main/frontend/common/utils/timings.spec.tsx
  src/main/frontend/common/utils/timings.tsx
  src/main/frontend/pipeline-console-view/app.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/ConsoleLogCard.spec.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/ConsoleLogCard.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/ConsoleLogStream.spec.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/DataTreeView.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/stage-details.spec.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/stage-details.tsx
  src/main/frontend/setupTests.js
  src/main/frontend/setupTests.ts
  src/main/resources/io/jenkins/plugins/pipelinegraphview/consoleview/PipelineConsoleViewAction/index.jelly
Labels: enhancement

#646 Remove string concatenation from logging
  src/main/java/io/jenkins/plugins/pipelinegraphview/consoleview/PipelineConsoleViewAction.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/treescanner/PipelineNodeTreeScanner.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineGraphApi.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineStepApi.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/legacy/PipelineNodeGraphVisitor.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/legacy/PipelineStepVisitor.java
Labels: chore

#645 Use React Tippy for dropdowns and tooltips
  package-lock.json
  package.json
  src/main/frontend/common/components/dropdown.tsx
  src/main/frontend/common/components/tooltip.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/ConsoleLogCard.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/pipeline-console.scss
  src/main/frontend/pipeline-console-view/pipeline-console/main/stage-details.tsx
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/support/convertLabelToTooltip.tsx
  src/main/frontend/pipeline-graph-view/pipeline-graph/styles/PipelineGraphWidget.scss
Labels: bugfix

#632 Improve stage view
  pom.xml
  src/main/frontend/common/i18n/i18n-provider.tsx
  src/main/frontend/common/i18n/translations.spec.ts
  src/main/frontend/common/i18n/translations.ts
  src/main/frontend/common/utils/timings.tsx
  src/main/frontend/multi-pipeline-graph-view/app.scss
  src/main/frontend/multi-pipeline-graph-view/app.tsx
  src/main/frontend/multi-pipeline-graph-view/multi-pipeline-graph/main/MultiPipelineGraph.tsx
  src/main/frontend/multi-pipeline-graph-view/multi-pipeline-graph/main/MultiPipelineGraphModel.ts
  src/main/frontend/multi-pipeline-graph-view/multi-pipeline-graph/main/SingleRun.tsx
  src/main/frontend/multi-pipeline-graph-view/multi-pipeline-graph/main/single-run.scss
  src/main/frontend/multi-pipeline-graph-view/multi-pipeline-graph/styles/MultiPipelineGraph.scss
  src/main/frontend/pipeline-console-view/app.tsx
  src/main/frontend/pipeline-console-view/index.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/ConsoleLogCard.spec.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/PipelineConsole.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/stage-details.tsx
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/PipelineGraph.tsx
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/PipelineGraphLayout.ts
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/PipelineGraphModel.tsx
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/support/nodes.scss
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/support/nodes.tsx
  src/main/frontend/pipeline-graph-view/pipeline-graph/styles/PipelineGraphWidget.scss
  src/main/java/io/jenkins/plugins/pipelinegraphview/multipipelinegraphview/PipelineRun.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineState.java
  src/main/resources/io/jenkins/plugins/pipelinegraphview/PipelineGraphViewAction/index.jelly
  src/main/resources/io/jenkins/plugins/pipelinegraphview/consoleview/PipelineConsoleViewAction/index.jelly
  src/main/resources/io/jenkins/plugins/pipelinegraphview/multipipelinegraphview/MultiPipelineGraphViewAction/index.jelly
  src/main/resources/io/jenkins/plugins/pipelinegraphview/multipipelinegraphview/MultiPipelineGraphViewAction/jobMain.jelly
  src/test/java/io/jenkins/plugins/pipelinegraphview/PipelineGraphViewRebuildTest.java
Labels: enhancement

#653 Remove legacy visitor implementations
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineGraphApi.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineStepApi.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/legacy/PipelineNodeGraphVisitor.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/legacy/PipelineStepVisitor.java
  src/test/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineGraphApiLegacyTest.java
  src/test/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineStepApiLegacyTest.java
Labels: chore

#648 Add a filter bar allowing users to filter by name and status
  src/main/frontend/common/components/dropdown.tsx
  src/main/frontend/common/components/filter.scss
  src/main/frontend/common/components/filter.tsx
  src/main/frontend/pipeline-console-view/app.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/ConsoleLogCard.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/DataTreeView.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/console-log-card.scss
  src/main/frontend/pipeline-console-view/pipeline-console/main/data-tree-view.scss
  src/main/frontend/pipeline-console-view/pipeline-console/main/providers/filter-provider.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/stage-details.scss
Labels: enhancement

#656 Do not create skeleton when the run is complete
  src/main/frontend/common/tree-api.ts
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/support/startPollingPipelineStatus.ts
Labels: bug

#659 Remove property for tooltip to follow cursor
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/support/convertLabelToTooltip.tsx
Labels: chore

#660 Use correct react property names
  src/main/frontend/pipeline-console-view/pipeline-console/main/DataTreeView.tsx
Labels: chore

#662 Update dependencies, fix tests warnings
  package-lock.json
  package.json
  src/main/frontend/common/i18n/translations.ts
  src/main/frontend/pipeline-console-view/pipeline-console/main/hooks/use-steps-poller.spec.ts
Labels: dependencies

#663 Migrate from Webpack to Rspack
  package-lock.json
  package.json
  rspack.config.js
Labels: chore

#667 Fix overlapping elements on job page
  src/main/resources/io/jenkins/plugins/pipelinegraphview/multipipelinegraphview/MultiPipelineGraphViewAction/jobMain.jelly
Labels: bug

#668 Add placeholder information whilst no runs are found on the job page
  src/main/frontend/common/i18n/translations.spec.ts
  src/main/frontend/common/i18n/translations.ts
  src/main/frontend/multi-pipeline-graph-view/app.tsx
  src/main/frontend/multi-pipeline-graph-view/multi-pipeline-graph/main/MultiPipelineGraph.tsx
  src/main/frontend/pipeline-console-view/app.tsx
  src/main/resources/io/jenkins/plugins/pipelinegraphview/Messages.properties
  src/main/resources/io/jenkins/plugins/pipelinegraphview/Messages_bg.properties
  src/main/resources/io/jenkins/plugins/pipelinegraphview/Messages_ca.properties
  src/main/resources/io/jenkins/plugins/pipelinegraphview/Messages_cs.properties
  src/main/resources/io/jenkins/plugins/pipelinegraphview/Messages_da.properties
  src/main/resources/io/jenkins/plugins/pipelinegraphview/Messages_de.properties
  src/main/resources/io/jenkins/plugins/pipelinegraphview/Messages_el.properties
  src/main/resources/io/jenkins/plugins/pipelinegraphview/Messages_es.properties
  src/main/resources/io/jenkins/plugins/pipelinegraphview/Messages_et.properties
  src/main/resources/io/jenkins/plugins/pipelinegraphview/Messages_fi.properties
  src/main/resources/io/jenkins/plugins/pipelinegraphview/Messages_fr.properties
  src/main/resources/io/jenkins/plugins/pipelinegraphview/Messages_he.properties
  src/main/resources/io/jenkins/plugins/pipelinegraphview/Messages_hu.properties
  src/main/resources/io/jenkins/plugins/pipelinegraphview/Messages_it.properties
  src/main/resources/io/jenkins/plugins/pipelinegraphview/Messages_ja.properties
  src/main/resources/io/jenkins/plugins/pipelinegraphview/Messages_ko.properties
  src/main/resources/io/jenkins/plugins/pipelinegraphview/Messages_lt.properties
  src/main/resources/io/jenkins/plugins/pipelinegraphview/Messages_lv.properties
  src/main/resources/io/jenkins/plugins/pipelinegraphview/Messages_nb_NO.properties
  src/main/resources/io/jenkins/plugins/pipelinegraphview/Messages_nl.properties
  src/main/resources/io/jenkins/plugins/pipelinegraphview/Messages_pl.properties
  src/main/resources/io/jenkins/plugins/pipelinegraphview/Messages_pt_BR.properties
  src/main/resources/io/jenkins/plugins/pipelinegraphview/Messages_pt_PT.properties
  src/main/resources/io/jenkins/plugins/pipelinegraphview/Messages_ro.properties
  src/main/resources/io/jenkins/plugins/pipelinegraphview/Messages_ru.properties
  src/main/resources/io/jenkins/plugins/pipelinegraphview/Messages_sk.properties
  src/main/resources/io/jenkins/plugins/pipelinegraphview/Messages_sl.properties
  src/main/resources/io/jenkins/plugins/pipelinegraphview/Messages_sr.properties
  src/main/resources/io/jenkins/plugins/pipelinegraphview/Messages_sv_SE.properties
  src/main/resources/io/jenkins/plugins/pipelinegraphview/Messages_tr.properties
  src/main/resources/io/jenkins/plugins/pipelinegraphview/Messages_uk.properties
  src/main/resources/io/jenkins/plugins/pipelinegraphview/Messages_zh_TW.properties
Labels: enhancement

#674 Update Stages empty state text
  src/main/resources/io/jenkins/plugins/pipelinegraphview/Messages.properties
Labels: chore

#677 Update renovate node filter to current LTS
  .github/renovate.json
Labels: chore

#678 Move timing translations to be local to plugin
  src/main/frontend/common/i18n/translations.spec.ts
  src/main/frontend/common/i18n/translations.ts
  src/main/frontend/multi-pipeline-graph-view/app.tsx
  src/main/frontend/pipeline-console-view/app.tsx
  src/main/resources/io/jenkins/plugins/pipelinegraphview/Messages.properties
  src/main/resources/io/jenkins/plugins/pipelinegraphview/Messages_bg.properties
  src/main/resources/io/jenkins/plugins/pipelinegraphview/Messages_da.properties
  src/main/resources/io/jenkins/plugins/pipelinegraphview/Messages_de.properties
  src/main/resources/io/jenkins/plugins/pipelinegraphview/Messages_es.properties
  src/main/resources/io/jenkins/plugins/pipelinegraphview/Messages_fr.properties
  src/main/resources/io/jenkins/plugins/pipelinegraphview/Messages_it.properties
  src/main/resources/io/jenkins/plugins/pipelinegraphview/Messages_ja.properties
  src/main/resources/io/jenkins/plugins/pipelinegraphview/Messages_nl.properties
  src/main/resources/io/jenkins/plugins/pipelinegraphview/Messages_pl.properties
  src/main/resources/io/jenkins/plugins/pipelinegraphview/Messages_pt_BR.properties
  src/main/resources/io/jenkins/plugins/pipelinegraphview/Messages_ru.properties
  src/main/resources/io/jenkins/plugins/pipelinegraphview/Messages_sr.properties
  src/main/resources/io/jenkins/plugins/pipelinegraphview/Messages_sv_SE.properties
  src/main/resources/io/jenkins/plugins/pipelinegraphview/Messages_tr.properties
  src/main/resources/io/jenkins/plugins/pipelinegraphview/Messages_zh_TW.properties
Labels: enhancement

#680 Encapsulate message format to translations
  src/main/frontend/common/RestClient.tsx
  src/main/frontend/common/i18n/i18n-provider.tsx
  src/main/frontend/common/i18n/index.ts
  src/main/frontend/common/i18n/messages.spec.ts
  src/main/frontend/common/i18n/messages.ts
  src/main/frontend/common/i18n/translations.spec.ts
  src/main/frontend/common/utils/timings.spec.tsx
  src/main/frontend/common/utils/timings.tsx
  src/main/frontend/multi-pipeline-graph-view/app.tsx
  src/main/frontend/multi-pipeline-graph-view/multi-pipeline-graph/main/MultiPipelineGraph.tsx
  src/main/frontend/pipeline-console-view/app.tsx
Labels: chore

#681 Catch Prettier, TypeScript, and ESLint issues in Jenkins
  .github/renovate.json
  .github/workflows/jenkins-security-scan.yml
  .prettierignore
  CONTRIBUTING.md
  LICENSE.md
  README.md
  package-lock.json
  package.json
  pom.xml
  vitest.config.ts
Labels: chore

#690 Add skeleton loader
  src/main/frontend/common/tree-api.ts
  src/main/frontend/pipeline-console-view/pipeline-console/main/PipelineConsole.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/components/skeleton.scss
  src/main/frontend/pipeline-console-view/pipeline-console/main/components/skeleton.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/hooks/use-steps-poller.ts
  src/main/frontend/pipeline-console-view/pipeline-console/main/pipeline-console.scss
Labels: enhancement

#694 Clear skeleton while build running
  src/main/frontend/common/tree-api.ts
Labels: bug

#687 Remove unused React imports
  eslint.config.js
  src/main/frontend/common/RestClient.tsx
  src/main/frontend/common/components/dropdown-portal.tsx
  src/main/frontend/common/components/dropdown.tsx
  src/main/frontend/common/components/filter.tsx
  src/main/frontend/common/components/status-icon.tsx
  src/main/frontend/common/components/tooltip.tsx
  src/main/frontend/common/i18n/i18n-provider.tsx
  src/main/frontend/common/i18n/index.ts
  src/main/frontend/common/utils/run-estimator.spec.ts
  src/main/frontend/common/utils/run-estimator.ts
  src/main/frontend/common/utils/stage-merge.spec.ts
  src/main/frontend/common/utils/stage-merge.ts
  src/main/frontend/common/utils/timings.spec.tsx
  src/main/frontend/common/utils/timings.tsx
  src/main/frontend/multi-pipeline-graph-view/app.tsx
  src/main/frontend/multi-pipeline-graph-view/index.tsx
  src/main/frontend/multi-pipeline-graph-view/multi-pipeline-graph/main/MultiPipelineGraph.tsx
  src/main/frontend/multi-pipeline-graph-view/multi-pipeline-graph/main/MultiPipelineGraphModel.ts
  src/main/frontend/multi-pipeline-graph-view/multi-pipeline-graph/main/SingleRun.tsx
  src/main/frontend/multi-pipeline-graph-view/multi-pipeline-graph/main/index.ts
  src/main/frontend/pipeline-console-view/app.tsx
  src/main/frontend/pipeline-console-view/index.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/Ansi.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/ConsoleLine.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/ConsoleLogCard.spec.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/ConsoleLogCard.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/ConsoleLogStream.spec.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/ConsoleLogStream.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/DataTreeView.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/PipelineConsole.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/StageNodeLink.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/StageView.spec.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/StageView.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/components/skeleton.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/components/stages-customization.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/components/stages.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/providers/filter-provider.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/providers/user-preference-provider.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/scroll-to-top-bottom.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/split-view.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/stage-details.spec.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/stage-details.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/stage-steps.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/symbols.tsx
  src/main/frontend/pipeline-graph-view/app.tsx
  src/main/frontend/pipeline-graph-view/index.tsx
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/PipelineGraph.tsx
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/index.ts
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/support/TruncatingLabel.tsx
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/support/connections.tsx
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/support/convertLabelToTooltip.tsx
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/support/labels.tsx
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/support/nodes.tsx
  tsconfig.json
Labels: chore

#695 Update React to 19
  package-lock.json
  package.json
Labels: enhancement
