Repository jenkinsci/pipeline-graph-view-plugin, pull requests merged in 2025-10, with the labels that each got.

#990 fix: fixed ANSI SGR codes for color reset
  src/main/frontend/pipeline-console-view/pipeline-console/main/Ansi.tsx
Labels: bug

#992 Remove unused ConsoleLogStreamProps.maxHeightScale
  src/main/frontend/pipeline-console-view/pipeline-console/main/ConsoleLogCard.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/ConsoleLogStream.spec.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/ConsoleLogStream.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/NoStageStepsFallback.tsx
Labels: chore

#989 feat: add support for ANSI bright colors
  src/main/frontend/pipeline-console-view/pipeline-console/main/Ansi.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/pipeline-console.scss
Labels: enhancement

#999 Update package-lock
  package-lock.json
Labels: chore

#1001 feat: add support for ANSI bold, dim, italic, underline and strike-through
  src/main/frontend/pipeline-console-view/pipeline-console/main/Ansi.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/pipeline-console.scss
Labels: enhancement

#1003 Fix reset of ANSI text attributes on global reset command
  src/main/frontend/pipeline-console-view/pipeline-console/main/Ansi.tsx
Labels: bug
