Repository jenkinsci/pipeline-graph-view-plugin, pull requests merged in 2025-06, with the labels that each got.

#806 Consider findWorstWarningBetween for branches of running builds
  src/main/java/io/jenkins/plugins/pipelinegraphview/analysis/StatusAndTiming.java
  src/test/java/io/jenkins/plugins/pipelinegraphview/analysis/StatusAndTimingTest.java
Labels: bug

#820 Set content type for plain text stage logs
  src/main/java/io/jenkins/plugins/pipelinegraphview/consoleview/PipelineConsoleViewAction.java
  src/test/java/io/jenkins/plugins/pipelinegraphview/PipelineGraphViewTest.java
  src/test/java/io/jenkins/plugins/pipelinegraphview/playwright/PipelineConsole.java
  src/test/resources/io/jenkins/plugins/pipelinegraphview/utils/gh817_unicodePlainTextLogs.jenkinsfile
Labels: bug

#821 Find in page only finds text in the visible area of the log
  package-lock.json
  package.json
  src/main/frontend/pipeline-console-view/pipeline-console/main/ConsoleLogStream.spec.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/ConsoleLogStream.tsx
  src/test/java/io/jenkins/plugins/pipelinegraphview/PipelineGraphViewTest.java
  src/test/java/io/jenkins/plugins/pipelinegraphview/playwright/PipelineConsole.java
  src/test/java/io/jenkins/plugins/pipelinegraphview/playwright/PipelineOverviewPage.java
  src/test/resources/io/jenkins/plugins/pipelinegraphview/utils/gh744_searchOffScreen.jenkinsfile
Labels: bug

#825 Set up VS Code for debugging Java and Frontend
  .gitignore
  .vscode/.gitignore
  .vscode/extensions.json
  .vscode/launch.json
  .vscode/settings.json
  .vscode/tasks.json
  CONTRIBUTING.md
Labels: chore

#827 Memoize `ConsoleLine`
  src/main/frontend/pipeline-console-view/pipeline-console/main/ConsoleLine.tsx
Labels: bug

#829 Stay in Pipeline Overview page when navigating to upstream build
  src/main/java/io/jenkins/plugins/pipelinegraphview/cards/items/UpstreamCauseRunDetailsItem.java
  src/test/java/io/jenkins/plugins/pipelinegraphview/cards/items/UpstreamCauseRunDetailsItemTest.java
Labels: enhancement

#832 Fix step header and stage tree not sticking
  src/main/frontend/pipeline-console-view/pipeline-console/main/components/stages.scss
  src/main/frontend/pipeline-console-view/pipeline-console/main/console-log-card.scss
  src/main/frontend/pipeline-console-view/pipeline-console/main/pipeline-console.scss
Labels: bugfix

#833 Highlight deep-linked log line
  src/main/frontend/pipeline-console-view/pipeline-console/main/ConsoleLine.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/ConsoleLogStream.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/console-log-card.scss
Labels: enhancement

#814 Add timings to stage view
  .vscode/tasks.json
  src/main/frontend/common/components/checkbox.tsx
  src/main/frontend/common/components/dropdown-portal.tsx
  src/main/frontend/common/components/dropdown.tsx
  src/main/frontend/common/components/symbols.tsx
  src/main/frontend/common/i18n/i18n-provider.tsx
  src/main/frontend/common/i18n/messages.ts
  src/main/frontend/common/user/user-preferences-provider.tsx
  src/main/frontend/multi-pipeline-graph-view/app.tsx
  src/main/frontend/multi-pipeline-graph-view/multi-pipeline-graph/main/SingleRun.tsx
  src/main/frontend/multi-pipeline-graph-view/multi-pipeline-graph/main/overfow-dropdown.tsx
  src/main/frontend/multi-pipeline-graph-view/multi-pipeline-graph/main/settings-button.scss
  src/main/frontend/multi-pipeline-graph-view/multi-pipeline-graph/main/settings-button.spec.tsx
  src/main/frontend/multi-pipeline-graph-view/multi-pipeline-graph/main/settings-button.tsx
  src/main/frontend/multi-pipeline-graph-view/multi-pipeline-graph/main/single-run.scss
  src/main/frontend/pipeline-console-view/app.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/PipelineConsole.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/stage-details.tsx
  src/main/frontend/pipeline-graph-view/app.tsx
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/PipelineGraph.tsx
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/PipelineGraphLayout.spec.ts
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/PipelineGraphLayout.ts
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/PipelineGraphModel.tsx
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/support/labels.tsx
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/support/nodes.tsx
  src/main/resources/io/jenkins/plugins/pipelinegraphview/Messages.properties
  src/main/resources/io/jenkins/plugins/pipelinegraphview/multipipelinegraphview/MultiPipelineGraphViewAction/index.jelly
  src/main/resources/io/jenkins/plugins/pipelinegraphview/multipipelinegraphview/MultiPipelineGraphViewAction/jobMain.jelly
  src/main/resources/io/jenkins/plugins/pipelinegraphview/multipipelinegraphview/MultiPipelineGraphViewAction/jobMain.properties
  src/main/webapp/js/card.js
Labels: enhancement

#846 Flatten skipped stage connections when collapsed (and redisplay timings)
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/PipelineGraphLayout.ts
Labels: enhancement

#856 Remove AbstractPipelineViewAction
  src/main/java/io/jenkins/plugins/pipelinegraphview/consoleview/PipelineConsoleViewAction.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/multipipelinegraphview/MultiPipelineGraphViewAction.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/AbstractPipelineViewAction.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineGraphApi.java
Labels: chore

#854 Redirect to new build on rebuild
  src/main/java/io/jenkins/plugins/pipelinegraphview/consoleview/PipelineConsoleViewAction.java
  src/main/resources/io/jenkins/plugins/pipelinegraphview/Messages.properties
  src/main/resources/io/jenkins/plugins/pipelinegraphview/consoleview/PipelineConsoleViewAction/index.jelly
  src/main/webapp/js/build.js
  src/test/java/io/jenkins/plugins/pipelinegraphview/PipelineGraphViewRebuildTest.java
Labels: enhancement

#857 Update duration formatting to use Intl.DurationFormat
  package-lock.json
  package.json
  pom.xml
  src/main/frontend/common/i18n/i18n-provider.tsx
  src/main/frontend/common/i18n/locale-provider.tsx
  src/main/frontend/common/i18n/messages.spec.ts
  src/main/frontend/common/i18n/messages.ts
  src/main/frontend/common/utils/timings.spec.tsx
  src/main/frontend/common/utils/timings.tsx
  src/main/frontend/multi-pipeline-graph-view/multi-pipeline-graph/main/MultiPipelineGraph.tsx
  src/main/resources/io/jenkins/plugins/pipelinegraphview/Messages.properties
  src/main/resources/io/jenkins/plugins/pipelinegraphview/Messages_bg.properties
  src/main/resources/io/jenkins/plugins/pipelinegraphview/Messages_da.properties
  src/main/resources/io/jenkins/plugins/pipelinegraphview/Messages_de.properties
  src/main/resources/io/jenkins/plugins/pipelinegraphview/Messages_es.properties
  src/main/resources/io/jenkins/plugins/pipelinegraphview/Messages_fr.properties
  src/main/resources/io/jenkins/plugins/pipelinegraphview/Messages_it.properties
  src/main/resources/io/jenkins/plugins/pipelinegraphview/Messages_ja.properties
  src/main/resources/io/jenkins/plugins/pipelinegraphview/Messages_nl.properties
  src/main/resources/io/jenkins/plugins/pipelinegraphview/Messages_pl.properties
  src/main/resources/io/jenkins/plugins/pipelinegraphview/Messages_pt_BR.properties
  src/main/resources/io/jenkins/plugins/pipelinegraphview/Messages_ru.properties
  src/main/resources/io/jenkins/plugins/pipelinegraphview/Messages_sr.properties
  src/main/resources/io/jenkins/plugins/pipelinegraphview/Messages_sv_SE.properties
  src/main/resources/io/jenkins/plugins/pipelinegraphview/Messages_tr.properties
  src/main/resources/io/jenkins/plugins/pipelinegraphview/Messages_zh_TW.properties
Labels: enhancement

#864 Linkify error text and step headers
  package-lock.json
  package.json
  src/main/frontend/pipeline-console-view/pipeline-console/main/ConsoleLine.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/ConsoleLogCard.tsx
Labels: bug

#866 Use custom rendering for input step
  src/main/frontend/common/RestClient.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/ConsoleLine.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/ConsoleLogCard.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/ConsoleLogStream.spec.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/console-log-card.scss
  src/main/frontend/pipeline-console-view/pipeline-console/main/steps/InputStep.tsx
  src/main/java/io/jenkins/plugins/pipelinegraphview/treescanner/PipelineNodeTreeScanner.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineInputStep.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineStep.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineStepApi.java
  src/main/resources/io/jenkins/plugins/pipelinegraphview/consoleview/PipelineConsoleViewAction/index.jelly
  src/test/java/io/jenkins/plugins/pipelinegraphview/consoleview/PipelineConsoleViewInputTest.java
Labels: bug
