Repository jenkinsci/pipeline-graph-view-plugin, pull requests merged in 2025-07, with the labels that each got.

#875 Reduce what gets linked
  src/main/frontend/common/utils/linkify-js.ts
  src/main/frontend/pipeline-console-view/pipeline-console/main/ConsoleLine.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/ConsoleLogCard.tsx
Labels: bug

#876 Fix Skipped icon color
  src/main/frontend/common/components/status-icon.tsx
Labels: bugfix

#880 Adjust spacing of details bar
  src/main/webapp/js/style.css
Labels: enhancement

#881 Improve stability of cancel tests
  src/test/java/io/jenkins/plugins/pipelinegraphview/PipelineGraphViewCancelTest.java
  src/test/java/io/jenkins/plugins/pipelinegraphview/playwright/PipelineOverviewPage.java
Labels: developer

#892 Remove Jackson usage as intermediary
  .gitignore
  src/main/java/io/jenkins/plugins/pipelinegraphview/consoleview/PipelineConsoleViewAction.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/multipipelinegraphview/MultiPipelineGraphViewAction.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/multipipelinegraphview/PipelineRun.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/AbstractPipelineNode.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineGraph.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineGraphApi.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineInputStep.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineStage.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineState.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineStep.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineStepList.java
  src/test/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineGraphApiTest.java
  src/test/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineStateTest.java
  src/test/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineStepApiTest.java
  src/test/java/io/jenkins/plugins/pipelinegraphview/utils/TestUtils.java
Labels: chore, developer

#894 Reduce network requests via caching and conditional GETs
  src/main/java/io/jenkins/plugins/pipelinegraphview/consoleview/PipelineConsoleViewAction.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/multipipelinegraphview/EtagBuilder.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/multipipelinegraphview/MultiPipelineGraphViewAction.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/multipipelinegraphview/PipelineRun.java
  src/test/java/io/jenkins/plugins/pipelinegraphview/multipipelinegraphview/EtagBuilderTest.java
  src/test/java/io/jenkins/plugins/pipelinegraphview/multipipelinegraphview/PipelineRunFactory.java
Labels: enhancement

#910 Rework polling of steps
  src/main/frontend/common/RestClient.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/hooks/use-steps-poller.spec.ts
  src/main/frontend/pipeline-console-view/pipeline-console/main/hooks/use-steps-poller.ts
  src/main/java/io/jenkins/plugins/pipelinegraphview/consoleview/PipelineConsoleViewAction.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineGraph.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineGraphApi.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineStepApi.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineStepList.java
Labels: bugfix

#917 Revert adding unneeded permission checks
  src/main/java/io/jenkins/plugins/pipelinegraphview/consoleview/PipelineConsoleViewAction.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/multipipelinegraphview/MultiPipelineGraphViewAction.java
Labels: bugfix

#918 Wrap details rather than overflowing
  src/main/webapp/js/style.css
Labels: bugfix

#908 Do not reset expanded steps while polling, only extend them
  src/main/frontend/pipeline-console-view/pipeline-console/main/hooks/use-steps-poller.spec.ts
  src/main/frontend/pipeline-console-view/pipeline-console/main/hooks/use-steps-poller.ts
Labels: bugfix

#912 Deduplicate fetching of console output
  src/main/frontend/common/RestClient.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/hooks/use-steps-poller.ts
  src/main/java/io/jenkins/plugins/pipelinegraphview/consoleview/PipelineConsoleViewAction.java
Labels: bugfix

#921 Improve detail bar on smaller screens
  src/main/frontend/pipeline-console-view/pipeline-console/main/stage-details.scss
Labels: bugfix

#926 Add build description
  src/main/java/io/jenkins/plugins/pipelinegraphview/consoleview/PipelineConsoleViewAction.java
  src/main/resources/io/jenkins/plugins/pipelinegraphview/consoleview/PipelineConsoleViewAction/index.jelly
  src/main/webapp/js/style.css
Labels: enhancement

#929 Remove --additional-height logic from graph when in the left position
  src/main/frontend/pipeline-console-view/pipeline-console/main/components/stages.scss
  src/main/frontend/pipeline-console-view/pipeline-console/main/components/stages.tsx
Labels: bug

#927 Fix underspecified react hooks and add linting for it
  eslint.config.js
  package-lock.json
  package.json
  src/main/frontend/common/i18n/i18n-provider.tsx
  src/main/frontend/common/tree-api.ts
  src/main/frontend/common/utils/live-total.tsx
  src/main/frontend/common/utils/timings.tsx
  src/main/frontend/multi-pipeline-graph-view/multi-pipeline-graph/main/MultiPipelineGraph.tsx
  src/main/frontend/multi-pipeline-graph-view/multi-pipeline-graph/main/SingleRun.tsx
  src/main/frontend/multi-pipeline-graph-view/multi-pipeline-graph/main/settings-button.spec.tsx
  src/main/frontend/multi-pipeline-graph-view/multi-pipeline-graph/main/settings-button.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/ConsoleLine.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/ConsoleLogCard.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/ConsoleLogStream.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/DataTreeView.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/hooks/use-steps-poller.ts
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/PipelineGraph.tsx
Labels: bug

#934 refactor: remove usage of commons-lang 2
  src/main/java/io/jenkins/plugins/pipelinegraphview/analysis/StatusAndTiming.java
  src/test/java/io/jenkins/plugins/pipelinegraphview/analysis/StatusAndTimingTest.java
Labels: developer
