Repository jenkinsci/pipeline-graph-view-plugin, pull requests merged in 2025-02, with the labels that each got.

#579 Fix isParameterized: Check the parameters used to build
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/AbstractPipelineViewAction.java
Labels: enhancement

#580 Rewrite rebuild actions using javascript java injection
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/AbstractPipelineViewAction.java
  src/main/resources/io/jenkins/plugins/pipelinegraphview/PipelineGraphViewAction/index.jelly
  src/main/resources/io/jenkins/plugins/pipelinegraphview/consoleview/PipelineConsoleViewAction/index.jelly
  src/main/resources/io/jenkins/plugins/pipelinegraphview/multipipelinegraphview/MultiPipelineGraphViewAction/index.jelly
  src/main/webapp/js/build.js
  src/test/java/io/jenkins/plugins/pipelinegraphview/PipelineGraphViewRebuildTest.java
Labels: enhancement

#581 CONTRIBUTING.md: Add some information to package the plugin
  CONTRIBUTING.md
Labels: documentation

#578 Update node symbols
  src/main/frontend/multi-pipeline-graph-view/multi-pipeline-graph/main/SingleRun.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/PipelineConsoleModel.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/TestData.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/pipeline-console.scss
  src/main/frontend/pipeline-graph-view/app.scss
  src/main/frontend/pipeline-graph-view/app.tsx
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/PipelineGraph.tsx
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/PipelineGraphLayout.spec.ts
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/PipelineGraphModel.tsx
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/support/StatusIcons.tsx
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/support/SvgStatus.tsx
  src/main/frontend/pipeline-graph-view/pipeline-graph/main/support/nodes.tsx
  src/main/frontend/pipeline-graph-view/pipeline-graph/styles/PipelineGraphWidget.scss
  src/main/frontend/step-status/StepStatus.tsx
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineGraphApi.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineStage.java
  src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineStageInternal.java
  src/main/resources/io/jenkins/plugins/pipelinegraphview/PipelineGraphViewAction/index.jelly
  src/main/resources/io/jenkins/plugins/pipelinegraphview/PipelineGraphViewAction/summary.jelly
  src/main/resources/io/jenkins/plugins/pipelinegraphview/consoleview/PipelineConsoleViewAction/index.jelly
  src/main/resources/io/jenkins/plugins/pipelinegraphview/multipipelinegraphview/MultiPipelineGraphViewAction/index.jelly
  src/main/resources/io/jenkins/plugins/pipelinegraphview/multipipelinegraphview/MultiPipelineGraphViewAction/jobMain.jelly
  src/main/resources/lib/pipeline-graph-view/symbols.jelly
Labels: enhancement

#592 Increase timeouts to handle AWS slowness
  src/test/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineStepApiTest.java
Labels: developer

#595 Don't show empty table heading when no builds
  src/main/frontend/multi-pipeline-graph-view/multi-pipeline-graph/main/MultiPipelineGraph.tsx
Labels: bug

#598 Provide Show more logs link in fullscreen step log
  src/main/frontend/pipeline-console-view/pipeline-console/main/ConsoleLogCard.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/ConsoleLogModal.tsx
Labels: bug
