Repository jenkinsci/pipeline-graph-view-plugin, pull requests merged in 2025-08, with the labels that each got.

#938 Avoid page navigation when selecting a log line
  src/main/frontend/pipeline-console-view/pipeline-console/main/ConsoleLine.tsx
  src/main/frontend/pipeline-console-view/pipeline-console/main/ConsoleLogStream.tsx
Labels: enhancement

#936 Fix scroll conflict between stickToBottom and selecting a log line
  src/main/frontend/pipeline-console-view/pipeline-console/main/ConsoleLogStream.tsx
Labels: bug

#954 Fix JUnit5 migration
  src/test/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineNodeUtilTest.java
Labels: chore

#953 Ban JUnit 4 imports
  pom.xml
Labels: chore
